server.port=8083

spring.docker.compose.file=services/order/compose.yaml, compose.yaml

# Показывать SQL-запросы в консоли
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Миграции
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.level.org.springframework.boot.liquibase.autoconfigure=DEBUG

# Конфиг кафки
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=saga
