server.port=8081

spring.cloud.gateway.server.webmvc.routes[0].id=inventory-route
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/inventory/**

spring.cloud.gateway.server.webmvc.routes[1].id=order-route
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/order/**

spring.cloud.gateway.server.webmvc.routes[2].id=payment-route
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/payment/**
